CREATE TABLE fe_lakewatch_catalog.lakewatch_field.cves_v5 (
  cve_id STRING NOT NULL COMMENT 'CVE identifier in the format CVE-YYYY-NNNNN.',
  cve_year INT COMMENT 'Year component of the CVE ID (e.g., 2026 for CVE-2026-12345).',
  state STRING COMMENT 'Publication state of the CVE record. Values: \'PUBLISHED\' (active), \'REJECTED\' (invalid / withdrawn). Filter to \'PUBLISHED\' for actionable analysis.',
  date_published TIMESTAMP COMMENT 'Timestamp when the CVE was first published. Use for recency filtering.',
  date_reserved TIMESTAMP COMMENT 'Timestamp when the CVE ID was reserved by a CNA (before publication details were available).',
  date_updated TIMESTAMP COMMENT 'Timestamp of the most recent update to the CVE record. Use to detect re-scored or re-classified vulnerabilities.',
  assigner_org_id STRING COMMENT 'Internal organization ID of the CVE Numbering Authority (CNA) that assigned this CVE.',
  assigner_short_name STRING COMMENT 'Short name of the assigning authority (e.g., \'mitre\', \'microsoft\', \'redhat\'). Useful for filtering by issuer or grouping by ecosystem.',
  title STRING COMMENT 'Short human-readable title of the CVE.',
  description STRING COMMENT 'Full natural-language description of the vulnerability. Use full-text search (ILIKE / contains) when keyword filtering is needed.',
  affected_products ARRAY<STRUCT<vendor: STRING, product: STRING, defaultStatus: STRING, platforms: ARRAY<STRING>, versions: ARRAY<STRUCT<version: STRING, status: STRING, lessThan: STRING, lessThanOrEqual: STRING, versionType: STRING>>>> COMMENT 'Array of structs describing affected products. Each entry has fields like vendor, product, defaultStatus, platforms, and versions. Use LATERAL VIEW EXPLODE to filter on vendor/product.',
  cvss_version STRING COMMENT 'CVSS specification version used for scoring. Values: \'2.0\', \'3.0\', \'3.1\', \'4.0\'.',
  cvss_base_score DOUBLE COMMENT 'Numeric CVSS base score (0.0-10.0). Higher is more severe.',
  cvss_severity STRING COMMENT 'Qualitative CVSS severity. Values: \'CRITICAL\', \'HIGH\', \'MEDIUM\', \'LOW\', \'NONE\'. Prefer this over cvss_base_score for human-friendly queries.',
  cvss_vector STRING COMMENT 'Raw CVSS vector string encoding the attack characteristics.',
  cvss_source STRING COMMENT 'Source that produced the CVSS score (\'CNA\' = CVE Numbering Authority, \'ADP\' = Authorized Data Publisher, typically CISA-ADP).',
  cwe_id STRING COMMENT 'Common Weakness Enumeration identifier (CWE-NNN) classifying the underlying weakness.',
  cwe_description STRING COMMENT 'Human-readable description of the CWE classification.',
  ssvc_exploitation STRING COMMENT 'SSVC (Stakeholder-Specific Vulnerability Categorization) — exploitation maturity. Values: \'active\' (in-the-wild exploitation), \'poc\' (proof-of-concept exists), \'none\' (no public exploitation). Filter to \'active\' for highest-priority CVEs.',
  ssvc_automatable STRING COMMENT 'SSVC — whether exploitation is automatable. Values: \'yes\', \'no\'. \'yes\' means an attacker can script exploitation at scale.',
  ssvc_technical_impact STRING COMMENT 'SSVC — severity of impact upon successful exploitation. Values: \'partial\', \'total\'.',
  references ARRAY<STRUCT<url: STRING, name: STRING, tags: ARRAY<STRING>>> COMMENT 'Array of structs containing reference URLs (vendor advisories, blog posts, exploit code). Each entry has url, name, and tags.',
  raw VARIANT COMMENT 'Raw VARIANT JSON of the original CVE v5 record. Use for fields not extracted into the silver layer.')
USING delta
COMMENT 'Silver-layer Delta table of CVE v5 (Common Vulnerabilities and Exposures version 5) records, sourced from MITRE/NVD and other CVE Numbering Authorities (CNAs). Each row is one CVE with structured metadata extracted from the original CVE v5 JSON: identifiers (cve_id, cve_year, assigner_*), lifecycle timestamps (date_reserved/published/updated), publication state, free-text title and description, an array of affected products (with vendors, products, platforms, and version ranges), CVSS scoring with CNA-preferred / CISA-ADP-fallback (cvss_version, cvss_base_score, cvss_severity, cvss_vector, cvss_source), CWE classification (cwe_id, cwe_description), SSVC priority signals (ssvc_exploitation, ssvc_automatable, ssvc_technical_impact), an array of references, and the original raw VARIANT record. Use the extracted columns directly for analytics; consult `raw` only for fields not surfaced into the silver layer. Always filter `state = \'PUBLISHED\'` to exclude rejected/invalid CVEs.'
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.enableVariantShredding' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.changeDataFeed' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.domainMetadata' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.variantShredding-preview' = 'supported',
  'delta.feature.variantType-preview' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')
